spring.application.name=pau
payment.api.endpoint=https://api.pau-banking.com/v2
spring.data.mongodb.uri=mongodb://localhost:27017/pau_db

spring.security.user.name=admin
spring.security.user.password=admin123

